### ISSUE TITLE
Q version dependence

### ISSUE THREAD

**Issue by danielecr** [kriskowal/q-io#100]
q-io depends on 1.0.1, not 2.0 version, is it outdated? or there are no plan to maintain or some missing "use instead ..." here too?
I just released an ebay trading api library based on it, https://github.com/danielecr/qebayapi , thus my concern.

**Comment by kriskowal** [comment]
I recommend depending only upon the v1 train of Q-IO, just as I recommend the v1 train of Q, and this recommendation applies to Joey, Collections, Jasminum, Mr, &c. There is a v2 branch of Q-IO that depends on the v2 branch of Q, but it is by no means stable, and I reserve the right to introduce backward compatibilities to any v2 branch until I say otherwise.

I will leave this open to track notes in READMEs.

**Comment by anton-rudeshko** [comment]
As far as I can see, [q-io depends on q@0.9.7...](https://github.com/kriskowal/q-io/blob/v1/package.json#L28)
This is not playing nicely with q@1.0.1 and makes me sad. Can we update?

**Comment by kriskowal** [comment]
@anton-rudeshko Yes, I’ll take care of that.

**Comment by anton-rudeshko** [comment]
Thank you, @kriskowal
