### ISSUE TITLE
q-io downloading or writing too much data in version 1.13

### ISSUE THREAD

**Issue by ghost** [kriskowal/q-io#145]
**Problem**

Version 1.13 of q-io is either downloading, or writing, approximately double the data it should in the script at:  http://pastebin.com/C6Q2HP22

**Last working version**

1.12.x

**First Noticed**

Yesterday (was not working from Sat to Mon)

**More info**

The resulting jmeter-29.tgz file should be ~25MB, and should extract with a tar -xf ..., and it does so correctly on version 1.12.x, but on 1.13 it produces a ~50MB file and does not extract.

If I had more time I'd try to determine if it were the q-io/fs or q-io/http calls, but I am busy with a release today.

**Comment by Stuk** [comment]
Looked into this and it's a result of https://github.com/kriskowal/q-io/pull/141.

The PR assumes that data without a content-type or charset is text/utf8 data, which is incorrect for binary data.

@Tomalak do you have time to look into this and fix? This is obviously a pretty major breaking issue.

**Comment by kriskowal** [comment]
I will revert the change and publish patch versions if @Tomalak can’t address this today.

**Comment by Tomalak** [comment]
@kriskowal I'm looking into this right now, give me a moment.

**Comment by kriskowal** [comment]
I’ll be around to support around 4:00. Will probably revert if it’s not looking hopeful by 8:00 PST. We can revisit the feature if it’s tractable.

**Comment by Tomalak** [comment]
@Stuk The point is, `.read()` is supposed to return a string, as per the API definition. If you don't want a string, just use `.request()`. (@kriskowal I realize it's a breaking change, but one towards the defined behavior. Not sure how best to progress)

**Comment by kriskowal** [comment]
@Tomalak My opinion is that `read` and `request` have the same stance on encoding. The difference is only that `read` accumulates its input, whether buffer or string.

**Comment by Stuk** [comment]
Yeah, the commented docs do say it returns a string, however I think we should follow the behaviour as it has been implemented.

Perhaps the solution involves a flag in the options object.

**Comment by kriskowal** [comment]
I like the idea of express `{"charset": "auto"}` (for both read and request) if the user wishes to receive a string or stream of strings in the absence of an explicit charset. I do not like the idea of forcing the output to be a String in either request or read. I do like the idea of having the option of requesting a string or stream of strings in read and request with `{"charset": "auto"}` and receiving a buffer or stream of buffers otherwise.

**Comment by kriskowal** [comment]
read returning a promise for string is a documentation bug. We do need to keep backward compat in v1. We can break it in v2, but opinions above apply to both.

**Comment by Tomalak** [comment]
Forcing the request to string was purely on the basis of the API docs.

It probably would be best to roll back the change for now and determine a clean strategy if and how Content-Type handling is supposed to work. 

I think it should be integrated into `request`, possibly with a MIME type whitelist for text conversion (`text/*` and a few `application` ones like `*/xml`, plus anything that has a `charset` parameter.)

Text data should be returned as string in any case, because - as argued before in #139 - the client has no way of determining the encoding of the stream without looking into the headers. Not decoding text properly in the library will lead to avoidable bugs in client code, IMHO.

**Comment by kriskowal** [comment]
Roger that. Thanks!

**Comment by kriskowal** [comment]
I’ve reverted the commit. There is a new backward compatible patch.

Upon looking closer, I have recalled some forgotten intentions and now think I got the current behavior wrong.

I had forgotten about flags. fs.open() produces a stream of strings in UTF-8 by default. fs.read() should as a consequence produce a string from UTF-8 by default to be consistent. If you want a buffer or stream of buffers from fs.open(), you have to specify `{flags: "b"}`.

HTTP is different in principle because it has a means of detecting the intended encoding. Looks like I defaulted request to buffers, with an express charset switching to strings, but inconsistently caused read to default to a string regardless of whether a charset was provided. This is an error, but we will have to fix it in v2.

I would like us to consider making HTTP and FS consistent. I would like in v2 for both to default to buffers  or streams of buffers for open, request, and read. I would like specifying a charset to be the sole means of switching to strings or streams of strings in both systems. I would like to support an "auto" charset in both cases. For the filesystem, auto would be UTF-8. For HTTP, the response content type header would  stand in for "auto". Any other explicit charset on request or read would override the MIME type of the response.

Since we have iconv-lite to play with, I would like readers and writers to support encode, decode, and transcode in v2.

**Comment by kriskowal** [comment]
Also, my apologies to @Tomalak for not catching this problem in review.

**Comment by Tomalak** [comment]
@kriskowal No worries, in the end it was my mistake, really. 

HTTP has the strong advantage over filesystem streams that the intended type and encoding of the following byte stream is declarable _at all_. Filesystem streams are open for wild guesses or finger-crossing (in other words, using a convention like UTF-8 - but good luck reading a file that really is Windows-1252 without prior knowledge). 

XML and some programming languages solve this through encoding declarations at the start of the file (e.g. [Python, via PEP 0263](https://www.python.org/dev/peps/pep-0263/)). But generally that's an open problem, so I think it's kind of hard to make HTTP and file system streams truly consistent. 

As a library user I would expect to never have to deal with streams/buffers when text is what I'm working with(*). For HTTP this is relatively easy to detect, for files it is much harder or even impossible.

---

(*) I appreciate that streams are desirable for large inputs, in which case I would also expect the user to be able to tell the expected encoding up-front.
