### ISSUE TITLE
`write()` resolves before content is written

### ISSUE THREAD

**Issue by nknapp** [kriskowal/q-io#149]
The following code-snippets seems not to work as expected in node 4.1:

``` js
var qfs = require('q-io/fs')
var fs = require('fs')

qfs.write('abc.txt', 'this is the file contents')
  // .delay(1000)
  .done(function () {
    console.log(fs.readFileSync('abc.txt', { encoding: 'utf-8'}))
  })
```

In nodejs 0.10.38, this outputs the line `this is the file contents`, in node 4.1.0, I only get an empty line in the output. It seems like the promise is resolved before the contents is written. Removing the comment in front of the `.delay(1000)` causes the correct line to appear.

**Comment by nknapp** [comment]
Using the `read()` function of `q-io/fs` also prints the correct line:

``` js
var qfs = require('q-io/fs')
qfs.write('abc.txt', 'this is the file contents')
  // .delay(1000)
  .done(function () {
    qfs.read('abc.txt').done(console.log)
  })
```

**Comment by kriskowal** [comment]
Thanks. A PR would be most welcome.

**Comment by nknapp** [comment]
Where is the `write()`-method defined? Shouldn't it be in `fs.js` somewhere?

**Comment by kriskowal** [comment]
Methods of streams are in one of the stream modules, and in particular interest for these purposes, the Node bindings for streams. I don’t recall the specific module off-hand. I may be of more assistance after business hours.

**Comment by gagern** [comment]
It isn't [`write`](https://github.com/kriskowal/q-io/blob/fa3915be3e898738c50995f9ccaf828889e5cadc/fs-common.js#L52-L88) which is broken, it's [`close`](https://github.com/kriskowal/q-io/blob/fa3915be3e898738c50995f9ccaf828889e5cadc/writer.js#L66-L94) which incorrectly assumes that we don't have a `finish` event, due to a [broken version comparison](https://github.com/kriskowal/q-io/pull/153).
