### ISSUE TITLE
Need 'qs' version updated to latest version to resolve Security Vulnerabilities

### ISSUE THREAD

**Issue by GaneshKaparapu** [kriskowal/q-io#178]

**Comment by kriskowal** [comment]
Thank you for reporting. I would review a PR. I will also like to review the new `qs` version in its entirety to ensure that updating is not introducing a supply chain attack. The last round of `qs` defects pertained to ReDoS, which requires the usage in Q-IO to forward user-defined regexen. I’m in general in favor of updating dependencies, and otherwise am interested in knowing whether the update prevents a real attack.
