### ISSUE TITLE
Reader does not include `node`

### ISSUE THREAD

**Issue by wmertens** [kriskowal/q-io#40]
The docs say that the Node.JS Stream is available on the Reader and Writer objects as the node attribute, but they don't have that.

It would be really nice if the Reader and Writer could be drop-in supersets of the Node 0.10 streams. I think it would only mean renaming read() to slurp() and exposing the underlying Stream methods as well as the JSGI forEach() and Q .next() methods.

(Actually, perhaps the JSGI forEach should be a decorator added by the JSGI framework when it encounters a stream object)

**Comment by kriskowal** [comment]
The underlying stream implementation has changed since I wrote Q-IO’s Reader and Writer wrappers. They really need to be rewritten to use promises to provide the back-pressure signal Node now understands. I also just added promise streams to Q, so this might be an opportunity to consolidate some functionality.

**Comment by wmertens** [comment]
So what is the new project you moved promise streams to and how happy are
you with it?

**Comment by kriskowal** [comment]
I have not factored it out of the Q "streams" branch yet. It will likely
end up in this repository.
