### ISSUE TITLE
Http server very slow

### ISSUE THREAD

**Issue by chrisprobst** [kriskowal/q-io#99]
Hi,

I just got into the whole promise/generator issue and tried q-io/http like so:

var http = require("q-io/http");
var Apps = require("q-io/http-apps");

http.Server(function(req, res) {
    return Apps.ok("Hello");
}).listen(8080); 

Now I did a very small and simple http benchmark using wrk and boom against:

var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(8080, '127.0.0.1');
console.log('Server running at http://127.0.0.1:8080/');

While I know that this not even remotely a serious test, I did notice a real difference.

Using the callback-hell version I got around 11200 req/sec and using q-io/http I got about 350 req/s. That's a couple of magnitudes slower.

Now, the difference can have multiple reasons. First, in the q-io/http version there is a lot more js involved and js is slow. I guess the callback version is so fast because basically there is almost no javascript involved and so it's a libuv benchmark basically.
Or it is some internal q-io stuff which takes some time.

Maybe you could help me solving this dilemma ;)

**Comment by kriskowal** [comment]
Just some general thoughts for now.

First and foremost, Q and Q-IO do need some attention regarding performance.
I am beginning to pay attention to speed, but need to develop additional infrastructure to gather meaningful metrics and run performance related experiments.

However, you are right to question the meaningfulness of this speed comparison.
This measures the overhead of using promises and promise streams for a simple Hello World server. That overhead is partially multiplicative, but probably dominated by a constant.
It would be much more insightful to compare the performance of apples for apples comparable sites.

However, even then, there is no way to get around the fact that Q and Q-IO promise streams are strictly overhead on callbacks and event emitters.
The right question to ask will always ultimately be, how do you want to program, and do promises and promise streams assist you as a developer, and are you willing to pay for that with this performance overhead.

In summary, we have a lot of work to do to vet this library.
For me, the first pass in design is user developer ergonomics.
The second is maintainer developer ergonomics.
In parallel is references, tutorials, and documentation.
I usually address performance when cases that call the viability of the library into question, though in the case of Node.js, dropping the abstraction entirely is always an option for specifically problematic cases.

Q-IO is very young by this standard. There are some bugs. The documentation has not progressed pass bare reference material. I am happy with the interface, but have been doing some refactoring to make it more maintainable and extensible. Some performance gains may have accidentally emerged from transitioning from closure style classes to prototypical classes. More powerful promise streams are coming in v2.

I hope you find this summary helpful in the interim, but at this time, this issue is not actionable.
